.TH xfs_mkfile 8
.SH NAME
xfs_mkfile \- create an XFS file
.SH SYNOPSIS
.nf
\f3xfs_mkfile\f1 [\f3\-v\f1] [\f3\-n\f1] \c
\f2size\f1[\f3k\f1|\f3b\f1|\f3m\f1|\f3g\f1] \f2filename\f1...
.fi
.SH DESCRIPTION
.I xfs_mkfile
creates one or more files.
The file is padded with zeroes by
default.
The default size is in bytes, but it can be
flagged as kilobytes, blocks, megabytes, or gigabytes with the \f3k\f1,
\f3b\f1, \f3m\f1, or \f3g\f1 suffixes, respectively.
.SH OPTIONS
.TP
\f3\-v\f1
Verbose.
Report the names and sizes of created files.
.TP
\f3\-n\f1
No bytes.
Create a holey file - that is,
do not write out any data, just
seek to end of file and write a block.
