.TH xfs_rtcp 8
.SH NAME
xfs_rtcp \- XFS realtime copy command
.SH SYNOPSIS
.nf
\f3xfs_rtcp\f1 [\f3\-e\f1 extsize] [\f3\-p\f1] \f2source\f1... \f2target\f1
.fi
.SH DESCRIPTION
.I xfs_rtcp
copies a file to the realtime partition on an XFS filesystem.
If there is more than one
.I source
and
.IR target ,
the final argument (the
.IR target )
must be a directory which already exists.
.SH OPTIONS
.TP
\f3\-e\f1 extsize
Sets the extent size of the destination realtime file.
.TP
\f3\-p\f1
Use if the size of the source file is not an even multiple of
the block size of the destination filesystem.
When
\f3\-p\f1 is specified
.I xfs_rtcp
will pad the destination file to a size which is an even multiple
of the filesystem block size.
This is necessary since the realtime file is created using
direct I/O and the minimum I/O is the filesystem block size.
.SH "SEE ALSO"
xfs(5),
mkfs.xfs(8),
mount(8).
.SH CAVEATS
Currently, realtime partitions are not supported under the Linux
version of XFS, and use of a realtime partition
.BR "WILL CAUSE CORRUPTION"
on the data partition.
As such, this command is made available for curious
.B "DEVELOPERS ONLY"
at this point in time.
